global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'api-gateway'
    static_configs:
      - targets: ['api-gateway:8080']

  - job_name: 'auth-service'
    static_configs:
      - targets: ['auth-service:8081']

  - job_name: 'user-service'
    static_configs:
      - targets: [ 'user-service:8082' ]

  - job_name: 'news-service'
    static_configs:
      - targets: [ 'news-service:8083' ]

  - job_name: 'postgres-auth'
    static_configs:
      - targets: ['postgres-auth-exporter:9187']

  - job_name: 'postgres-user'
    static_configs:
      - targets: [ 'postgres-user-exporter:9187' ]

  - job_name: 'postgres-news'
    static_configs:
      - targets: [ 'postgres-news-exporter:9187' ]