// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/dialect/sql/sqljson"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
	"github.com/neokofg/go-pet-detailed-microservices/auth-service/pkg/ent/personalaccesstoken"
	"github.com/neokofg/go-pet-detailed-microservices/auth-service/pkg/ent/predicate"
)

// PersonalAccessTokenUpdate is the builder for updating PersonalAccessToken entities.
type PersonalAccessTokenUpdate struct {
	config
	hooks    []Hook
	mutation *PersonalAccessTokenMutation
}

// Where appends a list predicates to the PersonalAccessTokenUpdate builder.
func (patu *PersonalAccessTokenUpdate) Where(ps ...predicate.PersonalAccessToken) *PersonalAccessTokenUpdate {
	patu.mutation.Where(ps...)
	return patu
}

// SetTokenHash sets the "token_hash" field.
func (patu *PersonalAccessTokenUpdate) SetTokenHash(s string) *PersonalAccessTokenUpdate {
	patu.mutation.SetTokenHash(s)
	return patu
}

// SetNillableTokenHash sets the "token_hash" field if the given value is not nil.
func (patu *PersonalAccessTokenUpdate) SetNillableTokenHash(s *string) *PersonalAccessTokenUpdate {
	if s != nil {
		patu.SetTokenHash(*s)
	}
	return patu
}

// SetName sets the "name" field.
func (patu *PersonalAccessTokenUpdate) SetName(s string) *PersonalAccessTokenUpdate {
	patu.mutation.SetName(s)
	return patu
}

// SetNillableName sets the "name" field if the given value is not nil.
func (patu *PersonalAccessTokenUpdate) SetNillableName(s *string) *PersonalAccessTokenUpdate {
	if s != nil {
		patu.SetName(*s)
	}
	return patu
}

// SetAbilities sets the "abilities" field.
func (patu *PersonalAccessTokenUpdate) SetAbilities(s []string) *PersonalAccessTokenUpdate {
	patu.mutation.SetAbilities(s)
	return patu
}

// AppendAbilities appends s to the "abilities" field.
func (patu *PersonalAccessTokenUpdate) AppendAbilities(s []string) *PersonalAccessTokenUpdate {
	patu.mutation.AppendAbilities(s)
	return patu
}

// SetLastUsed sets the "last_used" field.
func (patu *PersonalAccessTokenUpdate) SetLastUsed(t time.Time) *PersonalAccessTokenUpdate {
	patu.mutation.SetLastUsed(t)
	return patu
}

// SetNillableLastUsed sets the "last_used" field if the given value is not nil.
func (patu *PersonalAccessTokenUpdate) SetNillableLastUsed(t *time.Time) *PersonalAccessTokenUpdate {
	if t != nil {
		patu.SetLastUsed(*t)
	}
	return patu
}

// ClearLastUsed clears the value of the "last_used" field.
func (patu *PersonalAccessTokenUpdate) ClearLastUsed() *PersonalAccessTokenUpdate {
	patu.mutation.ClearLastUsed()
	return patu
}

// SetExpiresAt sets the "expires_at" field.
func (patu *PersonalAccessTokenUpdate) SetExpiresAt(t time.Time) *PersonalAccessTokenUpdate {
	patu.mutation.SetExpiresAt(t)
	return patu
}

// SetNillableExpiresAt sets the "expires_at" field if the given value is not nil.
func (patu *PersonalAccessTokenUpdate) SetNillableExpiresAt(t *time.Time) *PersonalAccessTokenUpdate {
	if t != nil {
		patu.SetExpiresAt(*t)
	}
	return patu
}

// SetUserID sets the "user_id" field.
func (patu *PersonalAccessTokenUpdate) SetUserID(u uuid.UUID) *PersonalAccessTokenUpdate {
	patu.mutation.SetUserID(u)
	return patu
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (patu *PersonalAccessTokenUpdate) SetNillableUserID(u *uuid.UUID) *PersonalAccessTokenUpdate {
	if u != nil {
		patu.SetUserID(*u)
	}
	return patu
}

// Mutation returns the PersonalAccessTokenMutation object of the builder.
func (patu *PersonalAccessTokenUpdate) Mutation() *PersonalAccessTokenMutation {
	return patu.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (patu *PersonalAccessTokenUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, patu.sqlSave, patu.mutation, patu.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (patu *PersonalAccessTokenUpdate) SaveX(ctx context.Context) int {
	affected, err := patu.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (patu *PersonalAccessTokenUpdate) Exec(ctx context.Context) error {
	_, err := patu.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (patu *PersonalAccessTokenUpdate) ExecX(ctx context.Context) {
	if err := patu.Exec(ctx); err != nil {
		panic(err)
	}
}

func (patu *PersonalAccessTokenUpdate) sqlSave(ctx context.Context) (n int, err error) {
	_spec := sqlgraph.NewUpdateSpec(personalaccesstoken.Table, personalaccesstoken.Columns, sqlgraph.NewFieldSpec(personalaccesstoken.FieldID, field.TypeInt))
	if ps := patu.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := patu.mutation.TokenHash(); ok {
		_spec.SetField(personalaccesstoken.FieldTokenHash, field.TypeString, value)
	}
	if value, ok := patu.mutation.Name(); ok {
		_spec.SetField(personalaccesstoken.FieldName, field.TypeString, value)
	}
	if value, ok := patu.mutation.Abilities(); ok {
		_spec.SetField(personalaccesstoken.FieldAbilities, field.TypeJSON, value)
	}
	if value, ok := patu.mutation.AppendedAbilities(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, personalaccesstoken.FieldAbilities, value)
		})
	}
	if value, ok := patu.mutation.LastUsed(); ok {
		_spec.SetField(personalaccesstoken.FieldLastUsed, field.TypeTime, value)
	}
	if patu.mutation.LastUsedCleared() {
		_spec.ClearField(personalaccesstoken.FieldLastUsed, field.TypeTime)
	}
	if value, ok := patu.mutation.ExpiresAt(); ok {
		_spec.SetField(personalaccesstoken.FieldExpiresAt, field.TypeTime, value)
	}
	if value, ok := patu.mutation.UserID(); ok {
		_spec.SetField(personalaccesstoken.FieldUserID, field.TypeUUID, value)
	}
	if n, err = sqlgraph.UpdateNodes(ctx, patu.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{personalaccesstoken.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	patu.mutation.done = true
	return n, nil
}

// PersonalAccessTokenUpdateOne is the builder for updating a single PersonalAccessToken entity.
type PersonalAccessTokenUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *PersonalAccessTokenMutation
}

// SetTokenHash sets the "token_hash" field.
func (patuo *PersonalAccessTokenUpdateOne) SetTokenHash(s string) *PersonalAccessTokenUpdateOne {
	patuo.mutation.SetTokenHash(s)
	return patuo
}

// SetNillableTokenHash sets the "token_hash" field if the given value is not nil.
func (patuo *PersonalAccessTokenUpdateOne) SetNillableTokenHash(s *string) *PersonalAccessTokenUpdateOne {
	if s != nil {
		patuo.SetTokenHash(*s)
	}
	return patuo
}

// SetName sets the "name" field.
func (patuo *PersonalAccessTokenUpdateOne) SetName(s string) *PersonalAccessTokenUpdateOne {
	patuo.mutation.SetName(s)
	return patuo
}

// SetNillableName sets the "name" field if the given value is not nil.
func (patuo *PersonalAccessTokenUpdateOne) SetNillableName(s *string) *PersonalAccessTokenUpdateOne {
	if s != nil {
		patuo.SetName(*s)
	}
	return patuo
}

// SetAbilities sets the "abilities" field.
func (patuo *PersonalAccessTokenUpdateOne) SetAbilities(s []string) *PersonalAccessTokenUpdateOne {
	patuo.mutation.SetAbilities(s)
	return patuo
}

// AppendAbilities appends s to the "abilities" field.
func (patuo *PersonalAccessTokenUpdateOne) AppendAbilities(s []string) *PersonalAccessTokenUpdateOne {
	patuo.mutation.AppendAbilities(s)
	return patuo
}

// SetLastUsed sets the "last_used" field.
func (patuo *PersonalAccessTokenUpdateOne) SetLastUsed(t time.Time) *PersonalAccessTokenUpdateOne {
	patuo.mutation.SetLastUsed(t)
	return patuo
}

// SetNillableLastUsed sets the "last_used" field if the given value is not nil.
func (patuo *PersonalAccessTokenUpdateOne) SetNillableLastUsed(t *time.Time) *PersonalAccessTokenUpdateOne {
	if t != nil {
		patuo.SetLastUsed(*t)
	}
	return patuo
}

// ClearLastUsed clears the value of the "last_used" field.
func (patuo *PersonalAccessTokenUpdateOne) ClearLastUsed() *PersonalAccessTokenUpdateOne {
	patuo.mutation.ClearLastUsed()
	return patuo
}

// SetExpiresAt sets the "expires_at" field.
func (patuo *PersonalAccessTokenUpdateOne) SetExpiresAt(t time.Time) *PersonalAccessTokenUpdateOne {
	patuo.mutation.SetExpiresAt(t)
	return patuo
}

// SetNillableExpiresAt sets the "expires_at" field if the given value is not nil.
func (patuo *PersonalAccessTokenUpdateOne) SetNillableExpiresAt(t *time.Time) *PersonalAccessTokenUpdateOne {
	if t != nil {
		patuo.SetExpiresAt(*t)
	}
	return patuo
}

// SetUserID sets the "user_id" field.
func (patuo *PersonalAccessTokenUpdateOne) SetUserID(u uuid.UUID) *PersonalAccessTokenUpdateOne {
	patuo.mutation.SetUserID(u)
	return patuo
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (patuo *PersonalAccessTokenUpdateOne) SetNillableUserID(u *uuid.UUID) *PersonalAccessTokenUpdateOne {
	if u != nil {
		patuo.SetUserID(*u)
	}
	return patuo
}

// Mutation returns the PersonalAccessTokenMutation object of the builder.
func (patuo *PersonalAccessTokenUpdateOne) Mutation() *PersonalAccessTokenMutation {
	return patuo.mutation
}

// Where appends a list predicates to the PersonalAccessTokenUpdate builder.
func (patuo *PersonalAccessTokenUpdateOne) Where(ps ...predicate.PersonalAccessToken) *PersonalAccessTokenUpdateOne {
	patuo.mutation.Where(ps...)
	return patuo
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (patuo *PersonalAccessTokenUpdateOne) Select(field string, fields ...string) *PersonalAccessTokenUpdateOne {
	patuo.fields = append([]string{field}, fields...)
	return patuo
}

// Save executes the query and returns the updated PersonalAccessToken entity.
func (patuo *PersonalAccessTokenUpdateOne) Save(ctx context.Context) (*PersonalAccessToken, error) {
	return withHooks(ctx, patuo.sqlSave, patuo.mutation, patuo.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (patuo *PersonalAccessTokenUpdateOne) SaveX(ctx context.Context) *PersonalAccessToken {
	node, err := patuo.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (patuo *PersonalAccessTokenUpdateOne) Exec(ctx context.Context) error {
	_, err := patuo.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (patuo *PersonalAccessTokenUpdateOne) ExecX(ctx context.Context) {
	if err := patuo.Exec(ctx); err != nil {
		panic(err)
	}
}

func (patuo *PersonalAccessTokenUpdateOne) sqlSave(ctx context.Context) (_node *PersonalAccessToken, err error) {
	_spec := sqlgraph.NewUpdateSpec(personalaccesstoken.Table, personalaccesstoken.Columns, sqlgraph.NewFieldSpec(personalaccesstoken.FieldID, field.TypeInt))
	id, ok := patuo.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "PersonalAccessToken.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := patuo.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, personalaccesstoken.FieldID)
		for _, f := range fields {
			if !personalaccesstoken.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != personalaccesstoken.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := patuo.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := patuo.mutation.TokenHash(); ok {
		_spec.SetField(personalaccesstoken.FieldTokenHash, field.TypeString, value)
	}
	if value, ok := patuo.mutation.Name(); ok {
		_spec.SetField(personalaccesstoken.FieldName, field.TypeString, value)
	}
	if value, ok := patuo.mutation.Abilities(); ok {
		_spec.SetField(personalaccesstoken.FieldAbilities, field.TypeJSON, value)
	}
	if value, ok := patuo.mutation.AppendedAbilities(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, personalaccesstoken.FieldAbilities, value)
		})
	}
	if value, ok := patuo.mutation.LastUsed(); ok {
		_spec.SetField(personalaccesstoken.FieldLastUsed, field.TypeTime, value)
	}
	if patuo.mutation.LastUsedCleared() {
		_spec.ClearField(personalaccesstoken.FieldLastUsed, field.TypeTime)
	}
	if value, ok := patuo.mutation.ExpiresAt(); ok {
		_spec.SetField(personalaccesstoken.FieldExpiresAt, field.TypeTime, value)
	}
	if value, ok := patuo.mutation.UserID(); ok {
		_spec.SetField(personalaccesstoken.FieldUserID, field.TypeUUID, value)
	}
	_node = &PersonalAccessToken{config: patuo.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, patuo.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{personalaccesstoken.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	patuo.mutation.done = true
	return _node, nil
}
