// Code generated by ent, DO NOT EDIT.

package ent

import (
	"time"

	"github.com/google/uuid"
	"github.com/neokofg/go-pet-detailed-microservices/news-service/pkg/ent/news"
	"github.com/neokofg/go-pet-detailed-microservices/news-service/pkg/ent/schema"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	newsFields := schema.News{}.Fields()
	_ = newsFields
	// newsDescTitle is the schema descriptor for title field.
	newsDescTitle := newsFields[1].Descriptor()
	// news.TitleValidator is a validator for the "title" field. It is called by the builders before save.
	news.TitleValidator = func() func(string) error {
		validators := newsDescTitle.Validators
		fns := [...]func(string) error{
			validators[0].(func(string) error),
			validators[1].(func(string) error),
		}
		return func(title string) error {
			for _, fn := range fns {
				if err := fn(title); err != nil {
					return err
				}
			}
			return nil
		}
	}()
	// newsDescContent is the schema descriptor for content field.
	newsDescContent := newsFields[2].Descriptor()
	// news.ContentValidator is a validator for the "content" field. It is called by the builders before save.
	news.ContentValidator = newsDescContent.Validators[0].(func(string) error)
	// newsDescImageURL is the schema descriptor for image_url field.
	newsDescImageURL := newsFields[3].Descriptor()
	// news.ImageURLValidator is a validator for the "image_url" field. It is called by the builders before save.
	news.ImageURLValidator = newsDescImageURL.Validators[0].(func(string) error)
	// newsDescCreatedAt is the schema descriptor for created_at field.
	newsDescCreatedAt := newsFields[5].Descriptor()
	// news.DefaultCreatedAt holds the default value on creation for the created_at field.
	news.DefaultCreatedAt = newsDescCreatedAt.Default.(func() time.Time)
	// newsDescUpdatedAt is the schema descriptor for updated_at field.
	newsDescUpdatedAt := newsFields[6].Descriptor()
	// news.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	news.DefaultUpdatedAt = newsDescUpdatedAt.Default.(func() time.Time)
	// news.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	news.UpdateDefaultUpdatedAt = newsDescUpdatedAt.UpdateDefault.(func() time.Time)
	// newsDescID is the schema descriptor for id field.
	newsDescID := newsFields[0].Descriptor()
	// news.DefaultID holds the default value on creation for the id field.
	news.DefaultID = newsDescID.Default.(func() uuid.UUID)
}
