apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: auth-service
  template:
    metadata:
      labels:
        app: auth-service
    spec:
      containers:
      - name: auth-service
        image: auth-service:latest
        ports:
        - containerPort: 9091
        - containerPort: 8081
        env:
        - name: DATABASE_URL
          valueFrom:
            secretKeyRef:
              name: postgres-auth-secret
              key: database-url
        - name: GRPC_PORT
          value: "9091"
        - name: HTTP_PORT
          value: "8081"
        - name: KAFKA_ADDR
          value: "kafka:9092"
---
apiVersion: v1
kind: Service
metadata:
  name: auth-service
spec:
  selector:
    app: auth-service
  ports:
  - name: grpc
    port: 9091
    targetPort: 9091
  - name: http
    port: 8081
    targetPort: 8081
